[services-ng] postgresql backup supports multiple versions
Change-Id: Ib1f41e2edf414561d6c248c4ef705ba60a323af7

diff --git a/ng/postgresql/bin/postgresql_backup b/ng/postgresql/bin/postgresql_backup
--- a/ng/postgresql/bin/postgresql_backup
+++ b/ng/postgresql/bin/postgresql_backup
@@ -18,8 +18,8 @@ module VCAP
     end
   end
 end
+
 class VCAP::Services::Postgresql::Backup < VCAP::Services::Base::Backup
-  IGNORE_DB = %w(postgres template0 template1)
 
   def default_config_file
     File.join(File.dirname(__FILE__), '..', 'config', 'postgresql_backup.yml')
@@ -33,11 +33,7 @@ class VCAP::Services::Postgresql::Backup < VCAP::Services::Base::Backup
       :service_name => @config["service_name"],
       :local_db => @config["local_db"],
       :backup_cmd => @config["backup_cmd"],
-      :host => @config["postgresql"]["host"],
-      :port => @config["postgresql"]["port"] || '5432',
-      :super_user => @config["postgresql"]["user"],
-      :super_passwd => @config["postgresql"]["pass"],
-      :database => @config["postgresql"]["database"],
+      :pg_config_by_version => @config["postgresql"],
       :backup_path => @config["backup_base_dir"]
     }
 
@@ -55,62 +51,44 @@ class VCAP::Services::Postgresql::Backup < VCAP::Services::Base::Backup
     # Enable ORM to get the information of provisioned services
     begin
       VCAP::Services::Postgresql::Node.setup_datamapper(:default, opts[:local_db])
-      VCAP::Services::Postgresql::Util::PGDBconn.init
     rescue => e
       # argument error
       echo "Exception while setting up the local database: #{e}"
       return 1
     end
 
-    service_class = VCAP::Services::Postgresql::Node::getProvisionedService(use_warden)
+    service_class = VCAP::Services::Postgresql::Node.pgProvisionedServiceClass(use_warden)
 
-    if use_warden
-      dbs = service_class.all
-    else
-      conn = VCAP::Services::Postgresql::Util::PGDBconn.connect(
-        :host => opts[:host],
-        :port => opts[:port].to_i,
-        :dbname => opts[:database],
-        :user => opts[:super_user],
-        :password => opts[:super_passwd])
-      result = conn.query("select * from pg_database;")
-      dbs = []
-      result.each {|db| dbs << db['datname'] }
-    end
+    dbs = service_class.all.map { |s| s.name }
 
     current_time = Time.now
 
     echo "Begin backup at #{current_time}"
     success, failed, ignored = [0,0,0]
-    dbs.each do |db|
-
-      if db.is_a?String
-        provisionedservice = service_class.get(db)
-        name = db
-      else
-        provisionedservice = db
-        name = db.name
-      end
-
-      if provisionedservice.nil?
-        # not provisioned database
-        if use_warden
-          result = -1
-        else
-          exe_user = opts[:super_user]
-          exe_passwd = opts[:super_passwd]
-          result = exe_backup_db(opts.merge({:name => name, :ts => current_time, :user => exe_user, :passwd => exe_passwd }))
-        end
+    dbs.each do |name|
+      provisionedservice = service_class.get(name)
+      unless provisionedservice
+        echo "The provisioned service with name #{name} does not exist!"
+        result = -1
       else
         # provisioed database
         default_user = provisionedservice.pgbindusers.all(:default_user => true)[0]
         if default_user.nil?
-          echo "The provisioned service with name #{name} has no default user ."
+          echo "The provisioned service with name #{name} has no default user."
           result = 1
         else
-          exe_user = default_user[:user]
-          exe_passwd = default_user[:password]
-          result = exe_backup_db(opts.merge({:name => name, :ts => current_time, :user => exe_user, :passwd => exe_passwd, :port => (provisionedservice.port||opts[:port])}))
+          version = provisionedservice.version
+          pg_config = opts[:pg_config_by_version][version] || {}
+          extra_opts = {
+            :name => name,
+            :ts => current_time,
+            :user => default_user[:user],
+            :passwd => default_user[:password],
+            :host => use_warden ? VCAP.local_ip : pg_config["host"],
+            :port => use_warden ? provisionedservice.port : pg_config["port"],
+            :dump_bin => pg_config["dump_bin"]
+          }
+          result = exe_backup_db(opts.merge(extra_opts))
         end
       end
 
@@ -128,21 +106,14 @@ class VCAP::Services::Postgresql::Backup < VCAP::Services::Base::Backup
     end
     echo "Backup begins at #{current_time} complete. Success: #{success}. Failed #{failed}. Ignored #{ignored}."
     0
-  ensure
-    conn.close if conn
   end
 
   def exe_backup_db(opts)
     backup_cmd, name, ts =
       %w(backup_cmd name ts).map{|k| opts[k.to_sym]}
-    if IGNORE_DB.include?(name)
-      echo "Ignore backup database #{name}."
-      return -1
-    else
-      # dir structure looks like \backups\<service-name>\<aa>\<bb>\<cc>\
-      # <aabbcc-rest-of-instance-guid>\<seconds_since_epoc>\<service specific data>
-      full_path = get_dump_path(name)
-    end
+    # dir structure looks like \backups\<service-name>\<aa>\<bb>\<cc>\
+    # <aabbcc-rest-of-instance-guid>\<seconds_since_epoc>\<service specific data>
+    full_path = get_dump_path(name)
     opts.merge!({:full_path => full_path})
 
     # options substitution
@@ -162,7 +133,7 @@ class VCAP::Services::Postgresql::Backup < VCAP::Services::Base::Backup
     echo "Backup for db #{name} complete in #{t2-t1} seconds."
     return res ? 0:1
   rescue => e
-    echo "Error when backup db #{opts[:name]}. #{e.backtrace.join("\n")}",true
+    echo "Error when backup db #{opts[:name]} for #{e}: #{e.backtrace.join("\n")}", true
     cleanup(full_path)
     return 1
   end
